# Generated by Django 4.1.6 on 2023-02-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_formadepagamento_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(
                default="000.000.000-00", max_length=15, unique=True, verbose_name="cpf"
            ),
            preserve_default=False,
        ),
    ]
