# Generated by Django 4.1.6 on 2023-02-15 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("equipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="funcionario",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="user_permissions",
        ),
        migrations.AddField(
            model_name="funcionario",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="funcionario",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="username",
            field=models.CharField(max_length=50),
        ),
    ]
